// <auto-generated />
namespace ProductManagerApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateusertable3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateusertable3));
        
        string IMigrationMetadata.Id
        {
            get { return "202012240321244_update-user-table-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
