// <auto-generated />
namespace ProductManagerApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_images_tablo_colums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_images_tablo_colums));
        
        string IMigrationMetadata.Id
        {
            get { return "202012222050203_change_images_tablo_colums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
