// <auto-generated />
namespace ProductManagerApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateusertable10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateusertable10));
        
        string IMigrationMetadata.Id
        {
            get { return "202012240404084_update-user-table-10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
