// <auto-generated />
namespace ProductManagerApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202012222142511_update_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
